data:
  train_path: "datasets/cleaned_data/spotify_v1/train.csv"
  test_path: "datasets/cleaned_data/spotify_v1/test.csv"
  target_column: "mode"

model:
  hidden_sizes: 64
  num_layers: 4
  activation: "sigmoid"
  learning_rate: 0.01
  epochs: 20
  batch_size: 128
  use_batchnorm: "True"
  dropout_rate: 0.5
  save_path: "model_checkpoints/neural_network.pth"

evaluation:
  save_path: "results/spotify_neural_network_results.json"